networks:
  default:
    name: ch-net

services:
  clickhouse-server:
    image: clickhouse:25.1.5.31
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: test123~
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./db:/var/lib/clickhouse
    ulimits:
      nofile: 262144 
